# Opciones de financiación para ramonelectronica_variador_SCADA_ESP32
github: [RamonElectronica]   # Tu usuario en GitHub Sponsors (si lo activas en el futuro)
patreon: ""                  # Vacío si no usas Patreon
open_collective: ""          # Vacío si no usas Open Collective
ko_fi: ""                    # Vacío si no usas Ko-fi
liberapay: ""                # Vacío si no usas Liberapay
buy_me_a_coffee: ""          # Vacío si no usas Buy Me a Coffee
custom: [
  "https://github.com/RamonElectronica",
  "https://instagram.com/ramonelectronica",
  "https://tiktok.com/@ramonelectronica",
  "https://www.facebook.com/ramonelectronicasoluciones.industriales",
  "https://ramonelectronica.great-site.net/"
]



